<a href="https://colab.research.google.com/github/syed-khader/learning-python-libraries/blob/main/pandasforgithub.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

numpy is used for mathamatical and scientific computations.
pandas is to structure the data and label the data

#pandas
-> it is a open source library of python
used for data analysis

-> pandas helps to performs :-
* data manipulation
* data transfromation
* data handling
* data cleaning
* data exploration

-> pandas stands for 'panel data structure'
which is a term used for statistics for multidimensional structured data.

-> pandas deals with two data structures i.e
1. series
2. dataframe


## limitation of numpy
numpy is also used in data analysis ie-
data cleaning, manipulating, transforming but there are certain limitations of it:
1. numpy stores data in homogenous
2. numpy is not having any structure to store the data

-> because of these limitations python has introduced pandas

In [5]:
'''
before using pandas we need to install it
syntax--> pip install pandas

after installing we need to import the library to the file
syntax--> import pandas as pd
'''
import pandas as pd

# series
* it is a 1-Dimensional label data structure.
* it has a single column of data.
* it is like a 1D array.

In [13]:
#creating a series
#syntax--> pd.series(1D array coll,name='col name')

snacks=pd.Series(['sandwich','momos','shawarma','samosa','bhelpuri','kerala chips','chowmein','mancurian'],name="snacks",index=[1,2,3,4,5,6,7,8])
snacks

1        sandwich
2           momos
3        shawarma
4          samosa
5        bhelpuri
6    kerala chips
7        chowmein
8       mancurian
Name: snacks, dtype: object

In [24]:
# create two series
# one list of your friends
# list of destinations you want to visit before you die

friends=pd.Series(['asim','atif','amir','harsh','shahank','jhon'],name="friends",index=[1,2,3,4,5,6])
friends

list_of_places=pd.Series(['kashmir','goa','sweden','amarica','japan',45],name="places",index=[1,2,3,4,5,6])
list_of_places

1    kashmir
2        goa
3     sweden
4    amarica
5      japan
6         45
Name: places, dtype: object

In [18]:
# Accessing values from series
#syntax--> var[index]
list_of_places[2]

#accessing multiple index position
list_of_places[[2,3,1]]

#access multiple values in a seq manner--> slicing
#syntax--> var[si:ei+-1:step]
list_of_places[2:4]

2        goa
3     sweden
1    kashmir
Name: places, dtype: object

In [22]:
snacks.ndim
snacks.size
snacks.shape
snacks.dtype

# we can perform all the attributes if array on series

dtype('O')

In [ ]:
# difference between series and array
'''
        array                                     series
1. it belongs to numpy                  1. it belongs to pandas
2. string is treated as string          2. string is treated as object
3. np.array(coll)                       3. pd.Series(coll)
4. we can create N dimension arrays     4. it can be only 1D
5. it can only store homogenous         5. can store heterogenous data