<a href="https://colab.research.google.com/github/syed-khader/learning-python-libraries/blob/main/pandasforgithub.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

numpy is used for mathamatical and scientific computations.
pandas is to structure the data and label the data

#pandas
-> it is a open source library of python
used for data analysis

-> pandas helps to performs :-
* data manipulation
* data transfromation
* data handling
* data cleaning
* data exploration

-> pandas stands for 'panel data structure'
which is a term used for statistics for multidimensional structured data.

-> pandas deals with two data structures i.e
1. series
2. dataframe


## limitation of numpy
numpy is also used in data analysis ie-
data cleaning, manipulating, transforming but there are certain limitations of it:
1. numpy stores data in homogenous
2. numpy is not having any structure to store the data

-> because of these limitations python has introduced pandas

In [1]:
'''
before using pandas we need to install it
syntax--> pip install pandas

after installing we need to import the library to the file
syntax--> import pandas as pd
'''
import pandas as pd

# series
* it is a 1-Dimensional label data structure.
* it has a single column of data.
* it is like a 1D array.

In [2]:
#creating a series
#syntax--> pd.series(1D array coll,name='col name')

snacks=pd.Series(['sandwich','momos','shawarma','samosa','bhelpuri','kerala chips','chowmein','mancurian'],name="snacks",index=[1,2,3,4,5,6,7,8])
snacks

1        sandwich
2           momos
3        shawarma
4          samosa
5        bhelpuri
6    kerala chips
7        chowmein
8       mancurian
Name: snacks, dtype: object

In [3]:
# create two series
# one list of your friends
# list of destinations you want to visit before you die

friends=pd.Series(['asim','atif','amir','harsh','shahank','jhon'],name="friends",index=[1,2,3,4,5,6])
friends

list_of_places=pd.Series(['kashmir','goa','sweden','amarica','japan',45],name="places",index=[1,2,3,4,5,6])
list_of_places

1    kashmir
2        goa
3     sweden
4    amarica
5      japan
6         45
Name: places, dtype: object

In [4]:
# Accessing values from series
#syntax--> var[index]
list_of_places[2]

#accessing multiple index position
list_of_places[[2,3,1]]

#access multiple values in a seq manner--> slicing
#syntax--> var[si:ei+-1:step]
list_of_places[2:4]

3     sweden
4    amarica
Name: places, dtype: object

In [5]:
snacks.ndim
snacks.size
snacks.shape
snacks.dtype

# we can perform all the attributes if array on series

dtype('O')

In [7]:
# difference between series and array
'''
        array                                     series
1. it belongs to numpy                  1. it belongs to pandas
2. string is treated as string          2. string is treated as object
3. np.array(coll)                       3. pd.Series(coll)
4. we can create N dimension arrays     4. it can be only 1D
5. it can only store homogenous         5. can store heterogenous data
'''

'\n        array                                     series\n1. it belongs to numpy                  1. it belongs to pandas\n2. string is treated as string          2. string is treated as object\n3. np.array(coll)                       3. pd.Series(coll)\n4. we can create N dimension arrays     4. it can be only 1D\n5. it can only store homogenous         5. can store heterogenous data\n'

## DataFrame

-> It is a 2-Dimensional datastructure of pandas.

-> It stores the data in a tabular manner having rows and columns.

-> It is a collection series

In [8]:
#Creating a dataframe
#Syntax-->pd.DataFrame(Dictionary)

df=pd.DataFrame({'Name':['Rahul','Raj','Harish','Sunil','Ganesh'],
                 'City':['KOL','MP','DEL','BBSR','MUM'],
                 'Age':[23,45,24,21,67]})
df

#Creating dataframe using nested list
#Syntax-->pd.DataFrame(data,columns=[col1,col2,...coln])

data=[['Manchurian','full',120],
      ['Chowmein','half',90],
      ['Samosa','half',20],
      ['Egg puff','full',40],
       ['Bonda',None,45]]

df1=pd.DataFrame(data,columns=['Item','Quantity','Price'])
df1

         Item Quantity  Price
0  Manchurian     full    120
1    Chowmein     half     90
2      Samosa     half     20
3    Egg puff     full     40
4       Bonda     None     45

In [9]:
'''Create a dataframe having 6 rows and colums like Name,Place,
Hobbie,Aim,Fav destination,Fav food '''

#Accessing a particular column data
#Syntacx-->df[colname]
df1['Quantity'][1]

df1['Quantity'].unique()  #Gives all the unique values present in column
df1['Quantity'].count()   #gives total number of non null values in a column
df1['Quantity'].value_counts()  #count of the unique values
df1['Quantity'].nunique()   #gives count of the unique values present in column
0
df1['Item'].nunique()
df1['Quantity'].count()
df1['Quantity'].nunique()
var=df1['Quantity'].value_counts()


#Access the index values from the series
#Syntax-->var.index
snacks.index

#Access the values from the series
#Syntax-->var.values
snacks.values

array(['sandwich', 'momos', 'shawarma', 'samosa', 'bhelpuri',
       'kerala chips', 'chowmein', 'mancurian'], dtype=object)

In [12]:
# sort the dataframe based on column
# syntax--> df.sort_values(by=col)

df1.sort_values(by='Item')
df.sort_values(['City','Age'])

     Name  City  Age
3   Sunil  BBSR   21
2  Harish   DEL   24
0   Rahul   KOL   23
1     Raj    MP   45
4  Ganesh   MUM   67

In [14]:
# Dataframe Attributes

df.shape
df.ndim
df.size
df.dtypes

#advantages of dataframes
'''
-> row labels
-> column labels
-> sorting
-> tabular structure
-> handling missing values
-> and new columns
-> filering
-> merging

Name    object
City    object
Age      int64
dtype: object

In [23]:
#info()-> infromation regarding the data present in dataframe
#syntax -> df.info()
df.info()

# head()--> gives the data from the top of the dataframe
#syntax--> df.head(n), n no of rows
# by default head() gives top 5 rows
df.head(2)

#tail()--> gives the data from the bottom of the dataframe
#syntax--> df.tail(n), n no of rows
# by default tail() gives bottom 5 rows
df.tail(2)

# describe() -- > gives the statistical information of the dataframe
# it works only on numarical column
# syntax --> df.describe()

# to include object information
# syntax--> df.describe(include=object)
df.describe(include=object)


# unique() fucntion --> gives the unique values for a particular column
# syntax--> df['col'].unique()
df['Name'].unique()

# df.columns is used to give column names in our data frame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   City    5 non-null      object
 2   Age     5 non-null      int64
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

Index(['Name', 'City', 'Age'], dtype='object')

In [44]:
prod=pd.DataFrame({'product': ['mobile phone','laptop','AC','washing machine','TV','air fryer','kettle'],'price':[35000,60000,50000,10000,60000,4000,1000]})
prod

# adding a new column
#syntax--> df[new_col]=value

prod['category']='electronics'
prod
prod['category']=['phones','electronics','appliance','appliance','appliance','appliance','appliance']
prod


#dropping a column
#syntax--> df.drop(col,axis=1,inplace=True)
prod.drop('category',axis=1,inplace=True)
prod

#inplace =True will modify the orignal dataframe/data source

#dropping a particular row using index
#syntax-> df.drop(index)
elec=prod.drop(3)
elec

#rename a column
# var={'old col':'new col'}
#df.rename(columns=var)

data={'price':'MRP'}
prod.rename(columns=data,inplace=True)
prod

           product    MRP
0     mobile phone  35000
1           laptop  60000
2               AC  50000
3  washing machine  10000
4               TV  60000
5        air fryer   4000
6           kettle   1000